// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Gateway.Automation.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProviderDetails
    {
        /// <summary>
        /// Initializes a new instance of the ProviderDetails class.
        /// </summary>
        public ProviderDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProviderDetails class.
        /// </summary>
        /// <param name="publishStatus">Possible values include: 'UnPublished',
        /// 'Requested', 'Published'</param>
        public ProviderDetails(System.Guid? id = default(System.Guid?), string providerName = default(string), System.Guid? subscriptionId = default(System.Guid?), string logo = default(string), string apiMarketplaceDescription = default(string), string publishStatus = default(string))
        {
            Id = id;
            ProviderName = providerName;
            SubscriptionId = subscriptionId;
            Logo = logo;
            ApiMarketplaceDescription = apiMarketplaceDescription;
            PublishStatus = publishStatus;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "providerName")]
        public string ProviderName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public System.Guid? SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logo")]
        public string Logo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "apiMarketplaceDescription")]
        public string ApiMarketplaceDescription { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'UnPublished', 'Requested',
        /// 'Published'
        /// </summary>
        [JsonProperty(PropertyName = "publishStatus")]
        public string PublishStatus { get; set; }

    }
}
