// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Gateway.Automation.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RateLimitPolicyResponse
    {
        /// <summary>
        /// Initializes a new instance of the RateLimitPolicyResponse class.
        /// </summary>
        public RateLimitPolicyResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RateLimitPolicyResponse class.
        /// </summary>
        /// <param name="entityType">Possible values include: 'Product',
        /// 'Api'</param>
        /// <param name="policyType">Possible values include: 'RateLimit',
        /// 'SetHeader', 'Custom'</param>
        public RateLimitPolicyResponse(System.Guid? id = default(System.Guid?), System.Guid? productId = default(System.Guid?), System.Guid? entityId = default(System.Guid?), string entityType = default(string), string policyType = default(string), string name = default(string), string description = default(string), int? calls = default(int?), int? renewalPeriod = default(int?))
        {
            Id = id;
            ProductId = productId;
            EntityId = entityId;
            EntityType = entityType;
            PolicyType = policyType;
            Name = name;
            Description = description;
            Calls = calls;
            RenewalPeriod = renewalPeriod;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public System.Guid? ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entityId")]
        public System.Guid? EntityId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Product', 'Api'
        /// </summary>
        [JsonProperty(PropertyName = "entityType")]
        public string EntityType { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'RateLimit', 'SetHeader',
        /// 'Custom'
        /// </summary>
        [JsonProperty(PropertyName = "policyType")]
        public string PolicyType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "calls")]
        public int? Calls { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "renewalPeriod")]
        public int? RenewalPeriod { get; set; }

    }
}
