// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Gateway.Automation.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ReportRecordListModel
    {
        /// <summary>
        /// Initializes a new instance of the ReportRecordListModel class.
        /// </summary>
        public ReportRecordListModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ReportRecordListModel class.
        /// </summary>
        public ReportRecordListModel(System.Guid? apimSubscriptionId = default(System.Guid?), string name = default(string), int? callCountSuccess = default(int?), int? callCountFailed = default(int?), int? callCountBlocked = default(int?), int? callCountOther = default(int?), int? callCountTotal = default(int?), long? bandwidth = default(long?))
        {
            ApimSubscriptionId = apimSubscriptionId;
            Name = name;
            CallCountSuccess = callCountSuccess;
            CallCountFailed = callCountFailed;
            CallCountBlocked = callCountBlocked;
            CallCountOther = callCountOther;
            CallCountTotal = callCountTotal;
            Bandwidth = bandwidth;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "apimSubscriptionId")]
        public System.Guid? ApimSubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "callCountSuccess")]
        public int? CallCountSuccess { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "callCountFailed")]
        public int? CallCountFailed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "callCountBlocked")]
        public int? CallCountBlocked { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "callCountOther")]
        public int? CallCountOther { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "callCountTotal")]
        public int? CallCountTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bandwidth")]
        public long? Bandwidth { get; set; }

    }
}
