// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Gateway.Automation.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RevisionResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the RevisionResponseModel class.
        /// </summary>
        public RevisionResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RevisionResponseModel class.
        /// </summary>
        public RevisionResponseModel(System.Guid? id = default(System.Guid?), System.Guid? apiId = default(System.Guid?), int? revisionNumber = default(int?), string revisionDescription = default(string), string openApiSpecUrl = default(string), bool? isCurrent = default(bool?))
        {
            Id = id;
            ApiId = apiId;
            RevisionNumber = revisionNumber;
            RevisionDescription = revisionDescription;
            OpenApiSpecUrl = openApiSpecUrl;
            IsCurrent = isCurrent;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "apiId")]
        public System.Guid? ApiId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "revisionNumber")]
        public int? RevisionNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "revisionDescription")]
        public string RevisionDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "openApiSpecUrl")]
        public string OpenApiSpecUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isCurrent")]
        public bool? IsCurrent { get; set; }

    }
}
