// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Gateway.Automation.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RevisionUpdateRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the RevisionUpdateRequestModel class.
        /// </summary>
        public RevisionUpdateRequestModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RevisionUpdateRequestModel class.
        /// </summary>
        public RevisionUpdateRequestModel(string revisionDescription = default(string), bool? isCurrent = default(bool?))
        {
            RevisionDescription = revisionDescription;
            IsCurrent = isCurrent;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "revisionDescription")]
        public string RevisionDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isCurrent")]
        public bool? IsCurrent { get; set; }

    }
}
